# Generated by Django 2.1 on 2018-08-22 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Videos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to='')),
                ('ip_link', models.TextField(blank=True, null=True)),
                ('line_coord_init_x', models.IntegerField(blank=True, null=True)),
                ('line_coord_init_y', models.IntegerField(blank=True, null=True)),
                ('line_coord_end_x', models.IntegerField(blank=True, null=True)),
                ('line_coord_end_y', models.IntegerField(blank=True, null=True)),
                ('processed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
