# Generated by Django 2.1.1 on 2018-09-13 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Algorithm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('data', models.CharField(max_length=500)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Logs', to='Algorithm.Videos')),
            ],
        ),
    ]
