# Generated by Django 2.1.1 on 2018-09-24 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Algorithm', '0003_auto_20180920_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videolog',
            name='moving_avg',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
